# Task: T303 | Spec: @specs/004-todo-ai-chatbot/spec.md §FR-001
# Constitution III: User Isolation - Pydantic schemas for API contracts with user_id validation

"""Pydantic schemas for chat and conversation endpoints."""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


# ============================================================================
# Conversation Schemas
# ============================================================================


class ConversationCreate(BaseModel):
    """
    Request schema for creating a new conversation.

    Auto-generated by backend - no input fields required.
    Backend will populate user_id from JWT claims and create timestamps.
    """

    pass


class ConversationResponse(BaseModel):
    """
    Response schema for conversation data.

    Reference: @specs/004-todo-ai-chatbot/plan.md Step 4 §Data Contracts
    """

    id: str = Field(..., description="Conversation ID (UUID)")
    user_id: str = Field(..., description="User ID (FK to users.id)")
    created_at: datetime = Field(..., description="Conversation creation timestamp (UTC)")
    updated_at: datetime = Field(..., description="Last update timestamp (UTC)")

    class Config:
        """Pydantic config."""

        from_attributes = True


# ============================================================================
# Message Schemas
# ============================================================================


class MessageCreate(BaseModel):
    """
    Request schema for creating a message (internal use only).

    Not exposed via API - used internally by message_service.
    """

    role: str = Field(..., description="Message role: 'user' or 'assistant'")
    content: str = Field(..., min_length=1, max_length=10000, description="Message content")


class MessageResponse(BaseModel):
    """
    Response schema for individual message data.

    Used in chat responses to display message history.
    Reference: @specs/004-todo-ai-chatbot/plan.md Step 4 §Data Contracts
    """

    id: str = Field(..., description="Message ID (UUID)")
    role: str = Field(..., description="Message role: 'user' or 'assistant'")
    content: str = Field(..., description="Message content (1-10000 chars)")
    created_at: datetime = Field(..., description="Message creation timestamp (UTC)")

    class Config:
        """Pydantic config."""

        from_attributes = True


# ============================================================================
# Chat Endpoint Schemas (API Request/Response Contracts)
# ============================================================================


class ChatRequestBody(BaseModel):
    """
    Request schema for POST /api/v1/chat endpoint.

    User sends a message and optionally specifies which conversation to use.
    If conversation_id is not provided, backend creates a new conversation.

    Reference: @specs/004-todo-ai-chatbot/spec.md §FR-001
    """

    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="User message to send to AI chatbot (1-2000 chars)",
    )

    conversation_id: Optional[str] = Field(
        default=None,
        description="Optional existing conversation ID. If not provided, creates new conversation.",
    )


class ChatResponseBody(BaseModel):
    """
    Response schema for POST /api/v1/chat endpoint.

    Backend returns AI response, conversation ID, and full message history.

    Reference: @specs/004-todo-ai-chatbot/spec.md §FR-001
    """

    response: str = Field(
        ...,
        description="AI assistant response to user message",
    )

    conversation_id: str = Field(
        ...,
        description="Conversation ID (used for subsequent messages in same chat)",
    )

    messages: List[MessageResponse] = Field(
        default_factory=list,
        description="Full conversation history (all messages in order, user + assistant)",
    )

    class Config:
        """Pydantic config."""

        from_attributes = True
